// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID        pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Address   string
	City      string
	State     string
	Zip       string
	Country   string
	CreatedAt pgtype.Timestamp
}
